site_url : https://asalvadorc.github.io/AD_BD_Relacionales_

site_name: AD - AccÃ©s a Dades

extra_css:
  - css/extra.css
  - css/copy-button.css

extra_javascript:
  - js/copy-button.js  

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

markdown_extensions:
  - admonition
  - toc:
      permalink: True 
  - tables    
  - attr_list

nav:

- Bases de Datos Relacionales:
  - ðŸ”¹RA y CE: RA_CE.md
  - ðŸ”¹IntroducciÃ³n: Introduccion.md
  - ðŸ”¹Herramientas y Conectores: Conectores.md
  - ðŸ”¹Operaciones sobre la BD: Operaciones.md
  #- ðŸ”¹Ejemplo completo en PostgreSQL: Estructura.md
  - ðŸ”¹Transacciones y control de errores: Transacciones.md
  - ðŸ”¹Funciones y Procedimientos almacenados: Procedimientos.md
  - ðŸ”¹Ejercicio obligatorio: Ejercicio.md
  # - Examen: Examen.md   