site_url : https://asalvadorc.github.io/AD_BD_Relacionales_

site_name: AD - AccÃ©s a Dades

extra_css:
  - css/extra.css

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

markdown_extensions:
  - admonition
  - toc:
      permalink: True 
  - tables    
  - attr_list

nav:

- UD 2. Bases de Datos Relacionales:
  - ğŸ”¹RA y CE: RA_CE.md
  - ğŸ”¹IntroducciÃ³n: Introduccion.md
  - ğŸ”¹ConexiÃ³n a un SGBD: Conectores.md
  - ğŸ”¹Operaciones sobre BD: Operaciones.md
  #- ğŸ”¹Ejemplo completo en PostgreSQL: Estructura.md
  - ğŸ”¹Transacciones y control de errores: Transacciones.md
  - ğŸ”¹Funciones y Procedimientos almacenados: Procedimientos.md
  